### ISSUE TITLE
global::operation() or delta::operation()

### ISSUE THREAD

**Issue by saiichihashimoto** [sanity-io/GROQ#111]
[sanity shows the `operation()` function under the `delta` namespace](https://www.sanity.io/docs/groq-functions#a64594a50318)

![image](https://github.com/sanity-io/groq-js/assets/2819256/d8d8f2b0-ad85-4e32-8ec6-0ed83a9e4437)

[The GROQ spec shows the `operation` function under the `global` namespace](https://sanity-io.github.io/GROQ/GROQ-1.revision1/#sec-global-operation-)

![image](https://github.com/sanity-io/groq-js/assets/2819256/0c6a682b-6dee-45ca-8548-eab779b4ee81)

[`groq-js` has it under the `delta` namespace](https://github.com/sanity-io/groq-js/blob/main/test/evaluate.test.ts#L237)

![image](https://github.com/sanity-io/groq-js/assets/2819256/7fc9e86a-9b20-4b4a-a113-d60115140a6b)

What's the truth? And can we get this all consolidated?

https://github.com/sanity-io/groq-js/issues/140

**Comment by judofyr** [comment]
Nice catch! Does https://github.com/sanity-io/GROQ/pull/114 look good?

**Comment by saiichihashimoto** [comment]
Looks good to me!
