### ISSUE TITLE
`-2**-2` Can be parsed two different ways

### ISSUE THREAD

**Issue by saiichihashimoto** [sanity-io/GROQ#112]
_Technically_, `-2**-2` can be parsed one of two ways while following the grammar, and the [precedence rules](https://sanity-io.github.io/GROQ/GROQ-1.revision1/#sec-Precedence-and-associativity) don't resolve which to choose:

1. `-(2**(-2))`
```
=> Expression
=> UnaryMinus
=> - Expression
=> - StarStar
=> - Expression ** Expression
=> - Number ** Expression
=> - 2 ** Expression
=> - 2 ** UnaryMinus
=> - 2 ** - Expression
=> - 2 ** - Number
=> - 2 ** - 2
```

2. `(-2*(*))-2`
```
=> Expression
=> Minus
=> Expression - Expression
=> Star - Expression
=> Expression * Expression - Expression
=> UnaryMinus * Expression - Expression
=> - Expression * Expression - Expression
=> - Number * Expression - Expression
=> - 2 * Expression - Expression
=> - 2 * Everything - Expression
=> - 2 * * - Expression
=> - 2 * * - Number
=> - 2 * * - 2
```

Obviously, the first option is what is intended. `groq-js` does this as well. But the grammar doesn't reflect this. For context, I'm typing `@sanity-typed/groq` and the tests I was writing for precedence ran into this case.

An easier way to think of this is that `2**` is valid and maybe it shouldn't be. (although, again, `groq-js` knows what's reasonable)

**Comment by judofyr** [comment]
Yes, I agree that this is not fully specified in the grammar as of today. I've pushed out a PR here: https://github.com/sanity-io/GROQ/pull/113. Does this look fine?

**Comment by saiichihashimoto** [comment]
My only feedback would be that nowhere else in the document is "lookahead" mentioned at all, so it might be confusing what is happening, if someone isn't familiar with how CFGs are implemented.

**Comment by judofyr** [comment]
I agree it's not perfect, but the syntax is part of [Spec Markdown](https://spec-md.com/) and should be quite easy to search for. Merging it for now, but also open for further suggestions for improvements.
