### ISSUE TITLE
Support for type casting

### ISSUE THREAD

**Issue by tomsseisums** [sanity-io/GROQ#17]
Support for, example:
```
*[_type == $type && string(numberCode) match "133*"]
```

To match documents where `numberCode`, while being a number, starts with `133`.

**Comment by judofyr** [comment]
This has certainly been on my mind and is something I want to add for support in the future.

**Comment by judofyr** [comment]
`string` was implemented in #38. I'm closing this issue and then we can instead open new issues for other coercions!
