### ISSUE TITLE
GROQ vs GraphQL?

### ISSUE THREAD

**Issue by tomByrer** [sanity-io/GROQ#18]
Seems like an interesting tool, but how is it better over GraphQL & the more popular servers for it?

**Comment by kmelve** [comment]
Hi! I'd recommend watching [this talk about GROQ and GraphQL](https://www.youtube.com/watch?v=Jcfubj2zRI0) and [this CSS-tricks article](https://css-tricks.com/the-best-graphql-api-is-one-you-write/) for more in-depth discussions on the topic. 

That being said, the main difference is that GROQ lets you fully query JSON-document(s) without having to define a schema or resolvers first. It's also more flexible in terms of the results you can compose without having to write custom resolvers. You can think of GraphQL more as an API-pattern like RESTful, while GROQ is a query language like SQL. At Sanity.io, we actually use GROQ when we generate our GraphQL API layer.
