### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by bbkane** [sanity-io/GROQ#22]
Hello. Your intro blog post says GROQ is open source, but I couldn't find any license in the repo. Please consider adding one.

**Comment by judofyr** [comment]
That's a very good point. What's a good open licence for a specification? CC?

**Comment by bbkane** [comment]
I'm totally not an expert in this. But from frantic Googling:

- Decide what you want to allow and disallow. Do you care if someone makes their own implementation of GROQ? Should they credit you? If so, how? Do you want the least amount of restrictions possible? What do you want to do about patents?

Links:

- CC variants: https://creativecommons.org/licenses/
- https://creativecommons.org/2008/03/29/what-good-is-a-cc-licensed-specification/ 
- MIT: https://opensource.stackexchange.com/questions/8380/is-mit-license-suitable-for-an-open-source-specification
- A [similar repo](https://github.com/microsoft/Kusto-Query-Language/blob/master/LICENSE) uses the Apache license

So... I dunno :)

**Comment by judofyr** [comment]
This has been added in 5788697ddecf1813c6a8889a995a7e6b2b352d99!
