### ISSUE TITLE
What types of ranges can be constructed?

### ISSUE THREAD

**Issue by judofyr** [sanity-io/GROQ#23]
Currently in the spec we have (https://github.com/sanity-io/GROQ/blame/15f7f28dcccff1fbf9c7f4c784ac7a2433faae39/spec/Section%204%20--%20Data%20types.md#L236-L248) a rule which says that it's not possible to construct a range of different types, but the groq-test-suite (https://github.com/sanity-io/groq-test-suite/blob/3a027e79b82e1a32462f1964fde19f6511b3e952/test/type/range.yml#L35-L53) also disallows creating ranges like `true .. false`.

I propose that ranges are allowed for any data type which are comparable (that is: number, string, boolean). I don't see that much value in supporting `boolean`, but it's at least consistent.

All other types of ranges (either ranges which has mixed types at the start/end or ranges between e.g. objects) will return `null`.

[1]: They are also used for slicing, but that uses a custom syntax which only supports a strict subset and is handled at parse-time)

**Comment by atombender** [comment]
Yeah, I don't know why we have those tests. Only valid ranges should be supported.
