### ISSUE TITLE
Serialization format for non-JSON types

### ISSUE THREAD

**Issue by atombender** [sanity-io/GROQ#29]
The JSON serialization of types like ranges and `=>` (pairs) don't seem to be documented, as far as I can see. HyperEngine returns ranges as pairs, while this is an error in the old engine.

**Comment by judofyr** [comment]
This is also now inconsistent between Sanity and GROQ-JS. I have three proposals here:

1. Arrays. `(1 .. 2)` => `[1, 2]` and `(1 => 2)` => `[1, 2]`. Disadvantage: There's no way of distinguishing between `..`, `...`, `=>`. This is how Sanity works today.
2. Objects: `(1 .. 2)` => `{"start": 1, "end": 2, "exclusive": false}` and `(1 => 2)` => `{"first": 1, "second": 2}`.
3. Null: Everything serializes as null.

I have a weak preference for 1 and 3 over 2.

**Comment by atombender** [comment]
I would pick 2, but not 1 or 3. I'm not a fan of "lossy" conversions. Reducing `1..2` to `[1, 2]` or similar is slightly nonsensical:

* Semantic meaning is lost
* It's not reversible since it's ambiguous
* It's not useful (any range can also be represented as an actual array)

We have two choices:

1. Preserve semantic meaning (and possibly allowing the JSON mapping to be fed back in through params).
  1.1. Represent as an object: `{"start": 1, "end": 2, "exclusive": false}`
  1.2. Represent the corresponding GROQ as a string ("the Postgres way"): `"1..2"`
2. Be clear that there's no JSON mapping. For example, something like a string: `"<RANGE>"`. In other words, a big red flag that shows this is data that is not representable.

But (2) is not useful (the value is junk), whereas (1) is, a little bit.

I wouldn't use `null`, as it's bound to be create confusion. There _is_ data here, just not straight JSON data.

**Comment by judofyr** [comment]
`1..2` is reduced to `[1, 2]` today in Sanity so one argument for that approach would be that it's less breaking change. Not it's a very strong argument.

Out of all the suggestions I think that I like "the Postgres way" best: When a user reads it they will most likely understand what it is, but it's an awkward format for machines to work with so it discourages people to depend on it. Pairs/ranges are after all mainly intended to be used internally and you shouldn't really return it. If you want an object which looks like `{start, end, exclusive}` you can always just project it yourself.

**Comment by atombender** [comment]
👍
