### ISSUE TITLE
Support sum() as a GROQ function

### ISSUE THREAD

**Issue by kmelve** [sanity-io/GROQ#35]
It would be handy to have the ability to sum numbers in GROQ. The syntax would be similar to count(). It should probably validate that it's a field of the type `Number` (or just be like JavaScript and sum whatever). 

```
*[_type == 'stats']{
    "pagestats": sum(pageStats[].pageLoads)
}
```

**Comment by kmelve** [comment]
I don't think it should be too hard to do, but I'll leave it to @judofyr to triage it.

**Comment by PaulPCIO** [comment]
I would also love to see this. Here is an example usecase

Example dataset
```json
{
    "_type":"invoice",
    "request":{
        "_ref":"...",
        "_type:":"reference"
    },
    "items":[
        {
            "itemId":1,
            "price":1000
        },
        {
            "itemId":2,
            "price":2000
        },
        {
            "itemId":3,
            "price":3000
        }
    ]
}
```

An example query where this would be super usefull
```ts
*[_type=="request" && _id == $id]{
    invoices: *[_type=="invoice" && reference(^._id)]{
        "totalPrice": sum(items[].price), // shows the total price of all the items eg; 6000
        items
    }
}[0]
```

**Comment by KenEucker** [comment]
Echoing this, would be nice to be able to add the up the size fields from the media in order to determine the size of a given group of media:

```
*[ _type in ["sanity.imageAsset", "sanity.fileAsset"] ]{"totalSize": sum(items[].size)}
```

**Comment by yob-yob** [comment]
any alternatives for the mean time? or do I really need to handle this JS side for now?

**Comment by atombender** [comment]
Hi everyone!

We have now launched this functionality as `math::sum()`, along with [a bunch more stuff](https://www.sanity.io/blog/groq-developer-update-september22).

We have also launched a new GROQ spec, which you can read about in our blog: **[Content is Queryable: (Re)Introducing GROQ](https://www.sanity.io/blog/content-is-queryable-groq)**.
