### ISSUE TITLE
Proposal: Keep null values in objects

### ISSUE THREAD

**Issue by judofyr** [sanity-io/GROQ#36]
The current behavior in Sanity today is to automatically remove `null` values from objects:

```js
{"a": null} // This returns {}
```

Note however that this is only done at projection. You can have a `null`-value in a document and it will be returned:

```
*[_type == "nullExample"][0]
// => {"_type": "nullExample", "key": null }

*[_type == "nullExample"][0]{_type,key}
// => {"_type": "nullExample" }
```

This spec (and groq-js) also includes the same "remove all `null`", but I'm not sure if that is what we want.

This is a proposal to allow `null` as values in objects.

Some implication:
- Due to the way `defined` and attribute lookup is defined there is no way of distinguishing between an attribute being `null` and not existing. `*[!defined(key)]` will return both objects where `key` does not exist and where `"key": null`.
- The current spec (and groq-js) had a way of removing attributes: `{..., "key": null}` would remove `key` (since setting it to `null` was equivalent to removing it). This "feature" will then be gone.

**Comment by atombender** [comment]
Agreed. We should treat `null` is a value, and should be preserved for consistency.
