### ISSUE TITLE
Support for behavior like Array.join()?

### ISSUE THREAD

**Issue by hangtwenty** [sanity-io/GROQ#44]
I think it seems reasonable to consider this because groq already has ways of restructuring (and reformatting) data; i.e. projections, functions, coalescing, and certain kinds of concatenation.

It's pretty common to want to stringify an array with a separator in between (like `, `). In Python, that's `[...].join(", ")`. In JS, it's `Array.join([...], ", ")`. (Putting those partly for sake of searches if someone looks for those and groq, that's what I searched for initially.) There's `CONCAT_WS` in SQL.

I figure this is a [Function](https://www.sanity.io/docs/query-cheat-sheet#functions-a1da4a3b2adc). I think it'd be consistent with the existing syntax to implement it like `join(<array>, ", ")` -- but to avoid confusion with database `JOIN`s, maybe it would be better to name it `strjoin(<array>, ", ")`.

Thoughts?

**Comment by judofyr** [comment]
This is definitely something we want to add!

Following the existing naming convention (e.g. `round`) I think it makes most sense to use `join` for this function, although I share your concern about it potentially being confusing.

We've briefly discussed that having namespaces would be useful (something like `string::join(…)`), and maybe time has come to introduce it.

However, considering how common this function is I think it's fine to introduce it as `join(…)` now and then later make it fit into a namespace.

Thoughts @atombender and @j33ty?

**Comment by atombender** [comment]
I'm fine with `join()` until the day we will consider adding "modules" to collect functions.

**Comment by atombender** [comment]
Hi! We have now launched this functionality as `array::join()`, along with [a bunch more stuff](https://www.sanity.io/blog/groq-developer-update-september22).

We have also launched a new GROQ spec, which you can read about in our blog: **[Content is Queryable: (Re)Introducing GROQ](https://www.sanity.io/blog/content-is-queryable-groq)**.
