### ISSUE TITLE
Dealing time offset (time zone) of datetime in tricky in JavaScript

### ISSUE THREAD

**Issue by judofyr** [sanity-io/GROQ#45]
**Situation:** The current specification of datetime says that a datetime should maintain its time offset: https://sanity-io.github.io/GROQ/#sec-Datetime. This implies that `{"a": dateTime("…+01:00")}` should serialize to `{"a": "…+01:00"}`.

**Complication:** This is sensible in itself, but causes problems in JavaScript since there's no way of converting a `Date` to a custom time offset. The only thing you can access is the local time zone (`getMinutes()`, `getSeconds()` …) and UTC time zone (`getUTCMinutes()`, `getUTCSeconds()`, …). It is possible to store the the offset separate from the `Date` and then manually adjust for it before formatting it, but this will require some complicated code.

**Solution 1:** Keep the existing semantic, and require more complicated code in groq-js.

**Solution 2:** Say that all datetimes are formatted in UTC time zone.

It should be mentioned that this only matters once you (1) need to do calculation on datetimes and (2) you end up returning them back to the user. For instance, in the query `*[dateTime(publishedAt) < now()]` it doesn't matter what the time offset is because we compare the universal time either way. It also won't matter in `*{publishedAt}` since this will not invoke any datetimes. It _will_ matter in `*{"a": dateTime(publishedAt) + 60}`.

Considering the limited use case I'd say that it's simpler to say that all datetimes are represented in UTC (`+00:00`).

**Comment by atombender** [comment]
Interesting that you can [get the zone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset), but it's interesting that you can't construct a date object with a specific time zone.

**Comment by rexxars** [comment]
I'm OK with using UTC. Theoretically we could support it using [luxon](https://moment.github.io/luxon/) until the [temporal proposal](https://github.com/tc39/proposal-temporal) is implemented everywhere, but it does add quite a bit of weight to the JS bundle.

**Comment by judofyr** [comment]
> it does add quite a bit of weight to the JS bundle.

About that: My current implementation in groq-js uses a few functions from date-fns. It imports them using ES6 imports so they should be tree-shakable. Do you see any problems with depending on date-fns?

**Comment by rexxars** [comment]
> Do you see any problems with depending on date-fns?

Not _really_, but do we actually need it? If the argument is always expected to be in RFC 3339, I think `new Date(date)` should be able to parse it just fine? The parse function in date-fns is ~7kB, so it would be nice to avoid if possible.
