### ISSUE TITLE
GROQ Search in a nested array doesn't work

### ISSUE THREAD

**Issue by kizim** [sanity-io/GROQ#48]
It looks like Sanity doesn't support search in a nested array.

I've created GROQ sandbox to demonstrate the issue: [https://groq.dev/01tEB1B3ZkvP4uqt2hQLOH](https://groq.dev/01tEB1B3ZkvP4uqt2hQLOH). I can run this query and the result is correct.

When I'm querying the Sanity GROQ endpoint there is no result:

![image](https://user-images.githubusercontent.com/11266157/105500484-04e6f880-5cd4-11eb-8c62-a8fff69bed0e.png)

But, if I specify an index for the first array it works:

![image](https://user-images.githubusercontent.com/11266157/105500513-0ca69d00-5cd4-11eb-9ba5-55f0e3372097.png)

```
*[
  _type == "ingredientsList" &&
  ("test" in ingredients[0].names[])
]{
  _id
}
```

**Comment by judofyr** [comment]
Can you try again now with version 2021-03-25? https://www.sanity.io/docs/api-versioning

**Comment by kmelve** [comment]
This should be fixed in the new API version. Closing this.
