### ISSUE TITLE
Ordering by field returns incorrect order

### ISSUE THREAD

**Issue by zackseuberling** [sanity-io/GROQ#55]
Howdy! I'm not sure how else to describe this, perhaps it's a data problem I'm not aware of with my fields.

I've paired down my groq query to show only the relevant bits of information, but hopefull it's enough

```
*[_type == "work"]{
  _id,
  title,
} | order(title asc)
```

And here's a screenshot of the Vision plugin running that query with the relevant bit of incorrect results:

![image](https://user-images.githubusercontent.com/1609558/113379937-c737c900-932f-11eb-8174-f9cde3746356.png)

You can see that `ALAXSXA | ALASKA` is before `Aan Yatx'u Saani: Noble People of the Land` but that isn't how I'd expect things to be sorted. In fact, what is additionally odd is that ordering by Title in the Studio orders things as I would expect them to be ordered:

![image](https://user-images.githubusercontent.com/1609558/113379997-e8001e80-932f-11eb-886b-9d94ab3ee76f.png)

So what is happening? Where are things going wrong? Apologies if this isn't the correct forum for this question.

**Comment by judofyr** [comment]
Strings in GROQ are ordered by Unicode code points, which means that uppercase letters are ordered before lowercase letters. If you want to ignore casing you can explicitly order by the lowercased version like this:

```
*[_type == "work"]{
  _id,
  title,
} | order(lower(title) asc)
```
