### ISSUE TITLE
Pipe operators return errors, starting from API version 2021-03-25

### ISSUE THREAD

**Issue by alevroub** [sanity-io/GROQ#65]
It seems like any query including an optional pipe operator is seen as a syntax error starting from API version `2021-03-25`.
So a query like: 
```
* | []
```
returns 

```
Query error: object or function expected

* | [
----^^
```
whereas `v1` returns all documents as expected. This isn't much of a problem for any pipeline components other than the map operator which doesn't work given the current behavior. 

**Edit:**
Despite the breaking changes for the map operator, there are still ways of getting specific values as an array with newer API versions:
```
*[] { one, two } { "_": [@.one, @.two] }._
```

**Comment by ofhope** [comment]
I was getting this error after updating API versions with a query ending in

```
| order(_createdAt asc) | [$from...$to]
```

Simply removing the pipe fixed it

```
| order(_createdAt asc) [$from...$to]
```

**Comment by alevroub** [comment]
True, but rewriting queries can be time consuming, and the error doesn't make sense in relation to the current documentation which still mentions implicit operators as a valid part of the syntax. So this just may be a documentation issue. However, considering that Sanity recommends configuring new clients using the current date, this becomes a huge breaking change in terms of syntax (forcing rewrites) and functionality (deprecating the map operator) which is [yet to be addressed](https://www.sanity.io/changelog?platforms=GROQ#a6473a5c1682) or documented.

**Comment by atombender** [comment]
We try to avoid breaking changes when we can, but sometimes they are hard to avoid. With the `v2021-03-25` API release, we did an almost complete rewrite of our internal query architecture, which resulted in a number of fixes to bugs such as the behaviour of `^`, nulls, `...`, array iteration, etc.

At the GROQ level, even bug fixes to query semantics are "breaking changes" — many people were relying on the legacy behaviour of `^`, for example — so we made a decision to use that opportunity to fix some historical mistakes, such as the pipe syntax.

I think the main problem here is that we didn't update all of the documentation. The issue with the pipe operator documentation has been reported internally before, but for some reason we haven't gotten the corrections out the door yet. I'll make sure the documentation team follows up on this.

> which is yet to be addressed.

What do you mean by this?

**Comment by alevroub** [comment]
I agree that it's a documentation issue. I don't mind the introduction of breaking changes when the point of API versioning is to encourage doing so. By _yet to be adressed_ I meant that the removal of implicit pipe operators is yet to be mentioned anywhere in the current documentation or the changelog since the `v2021-03-25` release.

**Comment by atombender** [comment]
Ah, I didn't realize the changelog did not include these changes. We will definitely rectify this. Thanks for letting us know!
