### ISSUE TITLE
Ordering does not work on array of attribute values

### ISSUE THREAD

**Issue by simonhrogers** [sanity-io/GROQ#66]
Hey Sanity team :-) 

So I can’t see this mentioned in the documentation but I noticed ordering doesn’t work in combination with an array of attribute values. It’s actually the first time I’ve attempted to use this pattern as I normally only want to order objects but it’s one I can see being helpful, if its possible to accommodate?

For instance this works:

`"artists": *[_type == "film"] | order(alphabetical asc) { artist }`

But this (my ideal scenario), doesn’t seem to: 

`"artists": *[_type == "film"].artist | order(alphabetical asc)`

I can’t find other mentions of this issue, but apologising in advance if I’m just not using correct terms! 

Thank you,

Simon

**Comment by alevroub** [comment]
What's happening is the second query is that the array you're passing to `order` doesn't have the `alphabetical` property and therefore nothing to sort by. With `v1` API you can sort and then flatten the array like so:
```
"artists": *[_type == "film"] | order(alphabetical asc) | [].artist
```
Normally you should be able to map and flatten the array but that's not working in newer API versions.
