### ISSUE TITLE
Using `pt::text()` function throws queryParseError

### ISSUE THREAD

**Issue by meszarosdezso** [sanity-io/GROQ#67]
I'm trying to implement full text search. My query looks like this:

```ts
const query = `*[ _type == 'post' && pt::text(content) match "*${val}*" ] {
  title,
}`

const response = await fetch(
  `https://[project-id].apicdn.sanity.io/v1/data/query/production?query=${encodeURIComponent(
      query
    )}`
  )
```

where `val` is the current value of the search input field.

But when using the new `pt::text()` function ( anywhere in the query, I also tried [this](https://www.sanity.io/schemas/word-count-and-reading-time-estimation-for-groq-and-portable-text-7470eab7) ) it throws `queryParseError` for missing parenthesis.

Here is the full response for the query above:

```ts
{
  description: "expected ']' following expression",
  end: 31,
  query: "*[ _type == 'post' && pt::text(content) match \"*something*\" ] {
      title,
    }",
  start: 1,
  type: "queryParseError"
}
```

When emitting the `pt::text()` part, it works fine.

Is this an issue with URL encoding the query, or am I missing something?

Thanks in advance.

**Comment by judofyr** [comment]
`pt::text` is only available in v2021-03-25 or later. This should work if you replace `v1` with e.g. `v2021-06-01`.
