### ISSUE TITLE
Proposal: add `min` and `max` functions

### ISSUE THREAD

**Issue by coreyward** [sanity-io/GROQ#68]
It would be exceedingly useful to be able to both filter on and retrieve values using minimum and maximum functions.

### Example 1
Fetching a value using a `max` function. This would be useful as an `initialValue` for an auto-incrementing order number field.

```groq
{
  "nextOrderNumber": max(*[_type == "order"].orderNumber) + 1
}
```

### Example 2
Filtering using a `min` function to retrieve products that have a variant under $20 (e.g. for display in a collection of low-cost add-on items). For clarity, this example assumes the `product` document has a `variants` field that is an array of objects that have a `priceInDollars` field on them.

```groq
*[_type == "product" && min(variants.priceInDollars) < 20]
```

**Comment by iamdagy** [comment]
This would be a great addition, it would solve a common situation of auto increment order numbers for instance.  👍

**Comment by judofyr** [comment]
Yes, we definitely want to add `min` and `max` (together with `avg` and `sum`)!

**Comment by atombender** [comment]
This took a while, but we have now launched min and max functions, along with [a bunch more functions](https://www.sanity.io/blog/groq-developer-update-september22)!
