### ISSUE TITLE
`score()` returns `null` when used in a joined query

### ISSUE THREAD

**Issue by troymcginnis** [sanity-io/GROQ#75]
# `score()` on joined queries
I'm attempting to organize posts by categories and further organize each grouping of posts in categories by a variety of variables. 

### Single Category Listing page
I'm using `score()` on each category listing page that looks like the following:

```js
*[_type == "post" && primaryCategory->slug.current == 'nhl'] | 
  score(
    "boston-bruins" in categories[].value.slug.current, 
    pt::text(content) match "Boston Bruins"
  ) | 
  order(_score desc, publishedDate desc) {
  _id,
  _score,
}[0..9]
```
**Data:**
```js
[
  {
    "_id": "nf-nhl-42073",
    "_score": 9.318251
  },
  {
    "_id": "nf-nhl-42067",
    "_score": 9.157886
  },
  {
    "_id": "nf-nhl-42072",
    "_score": 8.695723
  },
  {
    "_id": "nf-nhl-42078",
    "_score": 8.657026
  },
  {
    "_id": "nf-nhl-42097",
    "_score": 8.460868
  },
  // ...
]
```

### Main Listing page
However, on the main listing page, with groupings of categories, the query and results look as follows:

```js
*[_type == "category" && parent->slug.current == "league"] | order(categoryOrder) {
  _id,
  name,
  "posts": *[_type == "post" && references(^._id)] | 
    score(
      "boston-bruins" in categories[].value.slug.current, 
      pt::text(content) match "Boston Bruins"
    ) | 
    order(_score desc, publishedDate desc) {
    _id,
    _score,
  } [0..2]
}
```
**Output:**
```js
[
  {
    "_id": "c22f4b7f-1669-4349-9d6e-ad1c9c2aed39",
    "name": "NHL",
    "posts": [
      {
        "_id": "nf-nhl-42073",
        "_score": null
      },
      {
        "_id": "nf-nhl-42067",
        "_score": null
      },
      {
        "_id": "nf-nhl-42072",
        "_score": null
      }
    ]
  },
  // ...
]
```

# Questions
There are several **Gotchas** in the [official documentation](https://www.sanity.io/docs/groq-functions#be9f618a7086), but nothing to suggest that this isn't support. My assumption this is unsupported by the `score()` function based on the return of `null` rather than `0` or an actual score.

1. Is this indeed unsupported? Or am I just using it incorrectly?
2. Is this on the roadmap? (this would be an awesome feature to have)

**Comment by atombender** [comment]
This should work. If you can give me your project ID and dataset name, I can investigate. You can either email me or reach out to me by DM in the [community Slack](https://slack.sanity.io/), which is a better place for this kind of support problem.

**Comment by atombender** [comment]
Actually I'm able to reproduce the problem here.

**Comment by atombender** [comment]
We have a fix in testing that we'll probably get out today or Monday.

**Comment by atombender** [comment]
I guess I forgot to update this issue. The fix was released Oct 27. Closing this, but we can reopen if it's still a problem for you.

**Comment by kennyheard** [comment]
@atombender I think this might be the exact issue I'm currently having.

Here's the query I'm using:

```
*[_type == "instrumentType"] {
  "instruments": *[_type == "instrument" && references(^._id)] | score(title match "example") {
    title,
    _score
  }
}
```

Here's the result:

```
[…] 2 items
  0:{…} 1 property
    instruments:[…] 46 items
      0:{…} 2 properties
        title: Example
        _score: null
...
```

Running that same query as a standalone query, however:

```
*[_type == "instrument"] | score(title match "example") {
  title,
  _score
}
```

Shows the following:

```
instruments:[…] 80 items
  0:{…} 2 properties
    title: Example
    _score: 5.1123605
...
```

**Comment by atombender** [comment]
We have rolled out a fix for this. Can you try your query again, @kennyheard?
